### ISSUE TITLE
Making a text slider

### ISSUE THREAD

**Issue by BeyondMagic** [BeyondMagic/home#1]
I'll need help making a text slider, like these from the 20s and 90s of radios, showing each letter after it after the limit of the width; after that the letter back to the start and it continues infinitely as you know.

Tried making with padding-right 100%, margin-right, position relative and absolute (respectively from container and child), etc. Nothing seems to work, it would be lovely any help.

For now, I'm going to still work in other things...

**Comment by andreasgrafen** [comment]
Hoping that I got this right.. but I think this could help you with this issue: [CSS Marquee](https://www.w3schools.in/css3/css-marquee/)

**Comment by BeyondMagic** [comment]
Thank you, it's exactly that, my bad for not being so clear.
